openapi: 3.0.2

info:
  title: Device Service API
  description: Device service API description
  version: 0.1.0

servers:
- url: http://device-cloud.metathings.ai
  description: device cloud service address

paths:
  "/actions/issue_module_token":
    post:
      tags:
      - Device Cloud
      summary: Issue Module Token
      description: issue module token for module
      security: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - credential
              properties:
                credential:
                  $ref: "#/components/schemas/Credential"
                timestamp:
                  type: string
                nonce:
                  type: integer
                hmac:
                  type: string
            example:
              demo:
                $ref: "#/components/examples/IssueModuleTokenRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                properties:
                  token:
                    $ref: "#/components/schemas/Token"
              example:
                demo:
                  $ref: "#/components/examples/Token"
  "/actions/show_module":
    post:
      tags:
      - Device Cloud
      summary: Show Module By Token
      description: get module description by current token
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  module:
                    $ref: "#/components/schemas/Module"
              example:
                demo:
                  $ref: "#/components/examples/Module"
  "/actions/heartbeat":
    post:
      tags:
      - Device Cloud
      summary: Module Heartbeat to Device Cloud
      description: module heartbeat to device
      parameters:
      - in: header
        name: MT-Module-Session
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              properties:
                module:
                  $ref: "#/components/schemas/Module"
            example:
              demo:
                $ref: "#/components/examples/HeartbeatRequest"
      responses:
        "204":
          description: No Content
  "/actions/put_object":
    post:
      tags:
      - Device Cloud
      summary: Put Object into Simple Storage
      description: put object content into simple storage by module
      requestBody:
        content:
          application/json:
            schema:
              properties:
                object:
                  $ref: "#/components/schemas/Object"
                content:
                  type: string
            example:
              demo:
                $ref: "#/components/examples/PutObjectRequest"
      responses:
        "204":
          description: No Content
  "/actions/remove_object":
    post:
      tags:
      - Device Cloud
      summary: Remove Object in Simple Storage
      description: remove object in simple storage by module
      requestBody:
        content:
          application/json:
            schema:
              properties:
                object:
                  $ref: "#/components/schemas/Object"
            example:
              demo:
                $ref: "#/components/examples/RemoveObjectRequest"
      responses:
        "204":
          description: No Content
  "/actions/rename_object":
    post:
      tags:
      - Device Cloud
      summary: Rename Object in Simple Storage
      description: rename object from source to destination by module
      requestBody:
        content:
          application/json:
            schema:
              properties:
                source:
                  $ref: "#/components/schemas/Object"
                destination:
                  $ref: "#/components/schemas/Object"
            example:
              demo:
                $ref: "#/components/examples/RenameObjectRequest"
      responses:
        "204":
          description: No Content
  "/actions/get_object":
    post:
      tags:
      - Device Cloud
      summary: Get Object from Simple Storage
      description: get object from simple storage by module
      requestBody:
        content:
          application/json:
            schema:
              properties:
                object:
                  $ref: "#/components/schemas/Object"
            example:
              demo:
                $ref: "#/components/examples/GetObjectRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  object:
                    $ref: "#/components/schemas/Object"
              example:
                demo:
                  $ref: "#/components/examples/Object"
  "/actions/get_object_content":
    post:
      tags:
      - Device Cloud
      summary: Get Object Content from Simple Storage
      description: get object content form simple storage by module
      requestBody:
        content:
          application/json:
            schema:
              properties:
                object:
                  $ref: "#/components/schemas/Object"
            example:
              demo:
                $ref: "#/components/examples/GetObjectContentRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  content:
                    type: string
              example:
                demo:
                  $ref: "#/components/examples/GetObjectContentResponse"
  "/actions/list_objects":
    post:
      tags:
      - Device Cloud
      summary: List Objects from Simple Storage
      description: list objects from simple storage by module
      requestBody:
        content:
          application/json:
            schema:
              properties:
                object:
                  $ref: "#/components/schemas/Object"
            example: {}

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/Object"
              example:
                demo:
                  $ref: "#/components/examples/ListObjectsResponse"
  "/actions/push_frame_to_flow":
    post:
      tags:
      - Device Cloud
      summary: Push Frame To Device Cloud
      description: push data frame to device cloud
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
                flow:
                  $ref: "#/components/schemas/Flow"
                config_ack:
                  type: bool
                push_ack:
                  type: bool
            example:
              demo:
                $ref: "#/components/examples/PushFrameToFlowRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  session:
                    type: string
              example:
                demo:
                  $ref: "#/components/examples/PushFrameToFlowResponse"

security:
- bearerAuth: []

components:
  schemas:
    Credential:
      $ref: "../identityd2/model.yaml#/components/schemas/Credential"
    Token:
      $ref: "../identityd2/model.yaml#/components/schemas/Token"
    Module:
      $ref: "../deviced/model.yaml#/components/schemas/Module"
    Object:
      $ref: "../deviced/model.yaml#/components/schemas/Object"
  examples:
    Token:
      $ref: "../identityd2/example.yaml#/components/examples/Token"
    Module:
      $ref: "../deviced/example.yaml#/components/examples/Module"
    Object:
      $ref: "../deviced/example.yaml#/components/examples/Object"
    IssueModuleTokenRequest:
      value:
        credential:
          id: cdf279da5b44463f98d909b053e51932
        timestamp: 2006-01-02T15:04:05.999999999Z
        nonce: 0
        hmac: Ogr+LABFhmISdnNmqJWs3WI8i6npjN84cWAe04wi+W0=
    HeartbeatRequest:
      value:
        module:
          name: echo
    PutObjectRequest:
      value:
        object:
          device:
            id: 865889e11f19475fb8c0c3c8d126823a
          prefix: echo
          name: hello.txt
        content: "hello, world"
    RemoveObjectRequest:
      value:
        object:
          device:
            id: 865889e11f19475fb8c0c3c8d126823a
          prefix: echo
          name: hello.txt
    RenameObjectRequest:
      value:
        source:
          device:
            id: 865889e11f19475fb8c0c3c8d126823a
          prefix: echo
          name: hello.txt
        destination:
          device:
            id: 865889e11f19475fb8c0c3c8d126823a
          prefix: echo
          name: greet.txt
    GetObjectRequest:
      value:
        object:
          device:
            id: 865889e11f19475fb8c0c3c8d126823a
          prefix: echo
          name: hello.txt
    GetObjectContentRequest:
      value:
        object:
          device:
            id: 865889e11f19475fb8c0c3c8d126823a
          prefix: echo
          name: hello.txt
    GetObjectContentResponse:
      value:
        content: "hello, world"
    ListObjectsResponse:
      value:
        objects:
        - $ref: "#/components/examples/Object"
    PushFrameToFlowRequest:
      value:
        id: a39b15f6a2ea11e990a96c4008bb5d9a
        flow:
          name: temperature
        config_ack: true
        push_ack: true
    PushFrameToFlowResponse:
      value:
        id: a39b15f6a2ea11e990a96c4008bb5d9a
        session: e031306c61c04a9aad1ce7b38953977f

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
